parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\Broker\ExportConverter\ExportConverterInterface:
            tags: [ 'app.broker.export_converter' ]

    App\:
        resource: '../src/App/'
        exclude:
            - '../src/App/DependencyInjection/'
            - '../src/App/Entity/'
            - '../src/App/Kernel.php'
            - '../src/App/Tests/'
